project_id = "cctxifxnvqbwjnhurbaf"

[functions.chat]
verify_jwt = false

[functions.ask-ai]
verify_jwt = false

[functions.football-scores]
verify_jwt = false

[functions.security-stats]
verify_jwt = false



[functions.youtube-highlights]
verify_jwt = false
